-- Comentario linha única

/*
    Comentario de blocos
    Comentario de blocos
    Comentario de blocos
*/

SELECT current_timestamp FROM DUAL; -- todo select tem que ter um FROM // o DUAL é uma tabela que serve para isso


-- DDL

CREATE TABLE tb_filmes (
    filme_id      INTEGER
    titulo        VARCHAR(100) NOT NULL, -- NOT NULL é o obrigatório
    genero        VARCHAR(10) NOT NULL,
    classificacao VARCHAR(10) NOT NULL,
    diretor       VARCHAR(100) NOT NULL, -- atributo logico (varchar) , obrigatório ou não
    PRIMARY KEY (filme_id) -- CHAVE PRIMÁRIA 
);

INSERT INTO tb_filmes ( filme_id, titulo, genero, classificacao, diretor) -- inserir registro
                    VALUES ( 1,
                            'ZENI DO MAL', -- sempre aspas simples ''
                            'ANIMACAO',
                            '18',
                            'FELIX DO BEM');
                            

DROP TABLE tb_filmes; -- apaga a tabela

CREATE TABLE tb_filmes (
    filme_id      INTEGER GENERATED ALWAYS AS IDENTITY, -- Gera o id automaticamente sem repetições
    titulo        VARCHAR(100) NOT NULL, -- NOT NULL é o obrigatório
    genero        VARCHAR(10) NOT NULL,
    classificacao VARCHAR(10) NOT NULL,
    diretor       VARCHAR(100) NOT NULL, -- atributo logico (varchar) , obrigatório ou não
    PRIMARY KEY (filme_id) -- CHAVE PRIMÁRIA 
);

INSERT INTO tb_filmes ( titulo, genero, classificacao, diretor) -- tirou o id pq ele nao vai ser instanciado
                    VALUES ('ZENI DO MAL', -- não precisa mais do valor do id
                            'ANIMACAO',
                            '18',
                            'FELIX DO BEM');
                            
                            
    
    
    
    
    
CREATE TABLE tb_clientes(
    cliente_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome_cliente VARCHAR(30) NOT NULL,
    CONSTRAINT tb_clientes_pk PRIMARY KEY (cliente_id)
);

INSERT INTO tb_clientes (nome_cliente) VALUES ('HP');
INSERT INTO tb_clientes (cliente_id, nome_cliente) VALUES (67, 'HP');

