-- Comentario linha única

/*
    Comentario de blocos
    Comentario de blocos
    Comentario de blocos
*/

SELECT current_timestamp FROM DUAL; -- todo select tem que ter um FROM // o DUAL é uma tabela que serve para isso


-- DDL

CREATE TABLE tb_filmes (
    filme_id      INTEGER
    titulo        VARCHAR(100) NOT NULL, -- NOT NULL é o obrigatório
    genero        VARCHAR(10) NOT NULL,
    classificacao VARCHAR(10) NOT NULL,
    diretor       VARCHAR(100) NOT NULL, -- atributo logico (varchar) , obrigatório ou não
    PRIMARY KEY (filme_id) -- CHAVE PRIMÁRIA 
);

INSERT INTO tb_filmes ( filme_id, titulo, genero, classificacao, diretor) -- inserir registro
                    VALUES ( 1,
                            'ZENI DO MAL', -- sempre aspas simples ''
                            'ANIMACAO',
                            '18',
                            'FELIX DO BEM');
                            

DROP TABLE tb_filmes; -- apaga a tabela

CREATE TABLE tb_filmes (
    filme_id      INTEGER GENERATED ALWAYS AS IDENTITY, -- Gera o id automaticamente sem repetições
    titulo        VARCHAR(100) NOT NULL, -- NOT NULL é o obrigatório
    genero        VARCHAR(10) NOT NULL,
    classificacao VARCHAR(10) NOT NULL,
    diretor       VARCHAR(100) NOT NULL, -- atributo logico (varchar) , obrigatório ou não
    PRIMARY KEY (filme_id) -- CHAVE PRIMÁRIA 
);

INSERT INTO tb_filmes ( titulo, genero, classificacao, diretor) -- tirou o id pq ele nao vai ser instanciado
                    VALUES ('ZENI DO MAL', -- não precisa mais do valor do id
                            'ANIMACAO',
                            '18',
                            'FELIX DO BEM');
                            
    
    
CREATE TABLE tb_clientes(
    cliente_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome_cliente VARCHAR(30) NOT NULL,
    CONSTRAINT tb_clientes_pk PRIMARY KEY (cliente_id)
);

INSERT INTO tb_clientes (nome_cliente) VALUES ('HP');
INSERT INTO tb_clientes (cliente_id, nome_cliente) VALUES (67, 'HP');


CREATE TABLE TB_SALAS (
    SALA_ID   VARCHAR(3)  NOT NULL,
    NOME_SALA  VARCHAR(20) NOT NULL,
    TIPO_SALA  VARCHAR(5)  NOT NULL,
    CAPACIDADE INTEGER     NOT NULL,
    
    CONSTRAINT TB_SALAS_PK PRIMARY KEY (SALA_ID),
    CONSTRAINT TB_SALAS_CAPACIDADE_CK 
           CHECK (CAPACIDADE > 0),
    CONSTRAINT TB_SALAS_NOME_CK
            CHECK (LENGTH(nome_sala) > 5)        
);

-- FUNÇÃO ESCALARES

SELECT LENGTH('EDER') FROM DUAL; -- retorna o tamanho do texto EDER

CREATE TABLE TB_SESSOES(
 sessoes_id            INTEGER GENERATED ALWAYS AS IDENTITY,
 filme_id              INTEGER NOT NULL,
 sala_id               VARCHAR(3) NOT NULL,
 horario               TIMESTAMP NOT NULL,
 data_cadastro         DATE DEFAULT current_date,
 data_exibicao_inicio  DATE NOT NULL,
 data_exibicao_termino DATE NOT NULL,
 CONSTRAINT TB_SESSOES_PK PRIMARY KEY (sessoes_id),
 CHECK (data_exibicao_termino > data_exibicao_inicio),
 CHECK (data_exibicao_inicio > data_cadastro),
 UNIQUE (sala_id, horario, data_exibicao_inicio, data_exibicao_termino)
);

ALTER TABLE TB_SESSOES
 ADD CONSTRAINT TB_SESSOES_SALAS_FK
 FOREIGN KEY (sala_id)
 REFERENCES TB_SALAS(sala_id);
 
ALTER TABLE TB_SESSOES
 ADD CONSTRAINT TB_SESSOES_FK
  FOREIGN KEY (filme_id)
  REFERENCES TB_FILMES (filme_id);

CREATE TABLE TB_ASSENTOS (
    sala_id VARCHAR(3) NOT NULL,
    assento_id INTEGER GENERATED ALWAYS AS IDENTITY,
    fileira VARCHAR(1) NOT NULL,
    poltrona INTEGER NOT NULL,
    CONSTRAINT TB_ASSENTOS_PK PRIMARY KEY (assento_id),
    CONSTRAINT TB_ASSENTOS_SALA_FK
        FOREIGN KEY (sala_id)
        REFERENCES TB_SALAS (sala_id)
);

ALTER TABLE TB_ASSENTOS
ADD CONSTRAINT CHK_FILEIRA
CHECK (fileira BETWEEN 'A' AND 'J');

CREATE TABLE TB_INGRESSOS (
    ingresso_id     INTEGER GENERATED ALWAYS AS IDENTITY,
    cliente_id      INTEGER NOT NULL,
    sessoes_id      INTEGER NOT NULL,
    assento_id     INTEGER NOT NULL,
    data_exibicao   DATE NOT NULL,
    origem_compra   VARCHAR(10) NOT NULL,
    valor_pago      NUMBER NOT NULL,
    forma_pagamento VARCHAR(10) NOT NULL,
    tipo_ingresso   VARCHAR(20) NOT NULL,
    CONSTRAINT TB_INGRESSO_PK PRIMARY KEY(ingresso_id),
    CONSTRAINT TB_INGRESSOS_SESSOES_FK
        FOREIGN KEY (sessoes_id)
        REFERENCES TB_SESSOES (sessoes_id),
    CONSTRAINT TB_INGRESSOS_ASSENTO_FK
        FOREIGN KEY (assento_id)
        REFERENCES TB_ASSENTOS (assento_id),
    CONSTRAINT TB_INGRESSOS_CLIENTES_FK
        FOREIGN KEY (cliente_id)
        REFERENCES TB_CLIENTES (cliente_id)
);

ALTER TABLE TB_INGRESSOS
ADD CONSTRAINT CHK_VALOR_PAGO
CHECK (valor_pago > 0);

ALTER TABLE TB_INGRESSOS
ADD CONSTRAINT CHK_FORMA_PAGAMENTO
CHECK (forma_pagamento IN ('DINHEIRO', 'CARTAO', 'PIX'));

ALTER TABLE TB_INGRESSOS
ADD CONSTRAINT CHK_TIPO_INGRESSO
CHECK (tipo_ingresso IN ('INTEIRA', 'MEIA'));

ALTER TABLE TB_INGRESSOS
ADD CONSTRAINT CHK_ORIGEM_COMPRA
CHECK (origem_compra IN ('APLICATIVO', 'SITE', 'RECEPCAO'));
